---
layout: page
title: Software
excerpt: "Open source software contributions"
---

Here you can find my major contributions to open source software.

Development team member of 

- **Stan**: A probabilistic programming language [[Website](https://mc-stan.org/)]

Lead author and maintainer of

- **brms**: Bayesian Regression Models using Stan [[Website](https://paul-buerkner.github.io/brms), [GitHub](https://github.com/paul-buerkner/brms), [Blog-Posts](../software/brms-blogposts.html)]
- **posterior**: Tools for Working with Posterior Distributions [[GitHub](https://github.com/jgabry/posterior)]
- **thurstonianIRT**: Fit Thurstonian IRT models in R [[GitHub](https://github.com/paul-buerkner/thurstonianIRT)]

Author of

- **BayesFlow**: A Python library for simulation-based Bayesian inference [[GitHub](https://github.com/stefanradev93/BayesFlow)]
- **posteriordb**: A database of Bayesian posterior inference [[GitHub](https://github.com/stan-dev/posteriordb)]
- **loo**: Approximate leave-one-out cross-validation [[Website](https://mc-stan.org/loo), [GitHub](https://github.com/stan-dev/loo)]
- **bayesian**: An Interface from brms to tidymodels [[Website](https://hsbadr.github.io/bayesian/), [GitHub](https://github.com/hsbadr/bayesian)]

Contributed to

- **rstan**: R Interface to Stan [[Website](https://mc-stan.org/rstan), [GitHub](https://github.com/stan-dev/rstan)]
- **bayesplot**: Plotting Bayesian models [[Website](https://mc-stan.org/bayesplot), [GitHub](https://github.com/stan-dev/bayesplot)]
- **projpred**: Projection predictive variable selection [[Website](https://mc-stan.org/projpred), [GitHub](https://github.com/stan-dev/projpred)]
- **emmeans**: Estimating marginal means [[GitHub](https://github.com/rvlenth/emmeans)]

