---
title: Scientific Talks and Posters
excerpt: "A list of selected talks of me and my group"
toc-location: right
---

Below you can find a list of selected talks and posters of me and my group,
along with slides, paper references, and recordings when available.
Presenters are highlighted in **bold**.

- **Mukherjee, S.**, Claassen, M., & Bürkner, P. C. (2025). Contributed talk: *DGP-LVM: Derivative Gaussian process latent variable models*. 
Presented at [RSS International Conference](https://rss.org.uk/training-events/conference-2025/).
[Slides](pdf/derivative_gaussian_process_latent_variable_models2.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2404.04074){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- Mishra A., Habermann D., Schmitt M., Radev S. T., & **Bürkner P. C.** (2025). 
Contributed talk: *Robust Amortized Bayesian Inference with Self-Consistency Losses on Unlabeled Data*.
Presented at [BayesComp](https://bayescomp2025.sg/).
[Slides](pdf/SC_loss_real_data.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2501.13483){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Aguilar J. E.** & Bürkner P. C. (2025). 
Contributed talk: *Generalised Decomposition Priors on R2*.
Presented at [DAG Stat](https://dagstat2025.de/).
[Slides](pdf/GDR2_priors.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2401.10180){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Jedhoff S.** & Bürkner P. C. (2025). 
Contributed talk: *Efficient Bayesian Uncertainty Propagation*.
Presented at [DAG Stat](https://dagstat2025.de/).
[Slides](pdf/efficient_bayesian_uncertainty_propagation.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2505.10510){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2025). 
Invited talk: *Amortized Mixture and Multilevel Models*.
Presented at [One World Approximate Bayesian Inference Seminar](https://warwick.ac.uk/fac/sci/statistics/news/upcoming-seminars/abcworldseminar/).
[Slides](pdf/ABI_mixture_multilevel_models.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Mixture Paper](https://arxiv.org/abs/2501.10229){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Multilevel Paper](https://arxiv.org/abs/2408.13230){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2025). 
Invited talk: *The future of Bayes and brms with application in biology*.
Presented at the [Department of Biology, University of Bielefeld](https://www.uni-bielefeld.de/(en)/fakultaeten/biologie/index.xml).
[Slides](pdf/future_of_brms.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Software](../software#brms){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- Schmitt M., **Pratz V.**, Köthe U., Bürkner P. C., & Radev S. T. (2024).
Poster: *Consistency Models for Scalable and Fast Simulation-Based Inference*. 
Presented at [NeurIPS](https://neurips.cc).
[Poster](pdf/poster_consistency_models_SBI.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2312.05440){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Schmitt M.**, Ivanova D. R., Habermann D., Köthe U., Bürkner P. C., & Radev S. T. (2024). 
Poster: *Leveraging Self-Consistency for Data-Efficient Amortized Bayesian Inference*. 
Presented at [ICML](https://icml.cc/Conferences/2024).
[Poster](pdf/poster_self_consistency_ABI.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2310.04395){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- Fazio L., Scholz M., & **Bürkner P. C.** (2024). 
Contributed talk: *Generative Bayesian Modeling with Implicit Priors*. 
Presented at [StanCon](https://mc-stan.org/events/stancon2024/).
[Slides](pdf/implicit_priors.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2408.06504){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Mukherjee S.**, Claassen M., Bürkner P. C. (2024). 
Contributed talk: *DGP-LVM: Derivative Gaussian process latent variable models*.
Presented at [ICSDS](https://sites.google.com/view/ims-icsds2024/).
[Slides](pdf/derivative_gaussian_process_latent_variable_models.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2404.04074){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2024). 
Invited talk: *A Statistical Perspective on Simulation-Based Inference*.
Presented at [PHYSTAT-SBI](https://indico.cern.ch/event/1355601/).
[Slides](pdf/statistical_perspective_on_sbi.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Software](../software#bayesflow){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bockting F.**, Radev S. T., & Bürkner P. C. (2024). 
Contributed talk: *Normalizing Flows for Simulation Based Expert Prior Elicitation*. 
Presented at [MathPsych](https://mathpsych.org/conference/15/).
[Slides](pdf/deep_simulation_based_priors_mathpsych.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bockting F.**, Radev S. T., & Bürkner P. C. (2024). 
Contributed talk: *Simulation-Based Prior Knowledge Elicitation for Parametric Bayesian Models*. 
Presented at [ISBA Conference](https://www.unive.it/web/en/2208/home).
[Slides](pdf/simulation_based_priors_parametric_models_isba.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](http://arxiv.org/abs/2308.11672){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bockting F.**, Radev S. T., & Bürkner P. C. (2024). 
Invited talk: *Simulation-Based Prior Knowledge Elicitation for Parametric Bayesian Models*. 
Presented at [Bayes@Lund](https://www.bayesatlund.com/).
[Slides](pdf/simulation_based_priors_parametric_models.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Youtube](https://youtu.be/KFPn7P2mfQw){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](http://arxiv.org/abs/2308.11672){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2024). 
Keynote: *Does Bayes have to be slow? A glimpse into amortized Bayesian inference*.
Presented at [Bayes on the Beach](https://research.qut.edu.au/qutcds/bayes-onthe-beach/).
[Slides](pdf/glimpse_amortized_bayesian_inference.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://proceedings.mlr.press/v216/radev23a.html){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Software](../software#bayesflow){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- Schmitt M. & **Bürkner P. C.** (2024). 
Workshop: *Amortized Bayesian Inference with BayesFlow*.
Presented at [Bayes on the Beach](https://research.qut.edu.au/qutcds/bayes-onthe-beach/).
[Notebook](https://tiny.cc/botb-abi){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Software](../software#bayesflow){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2023). 
Keynote: *Bayesian Probabilistic Modeling for Ecology*.
Presented at [Oxford University](https://www.biology.ox.ac.uk/home).
[Slides](pdf/bayesian_inference_ecology.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2023).
Invited talk: *Testing evidence of absence with Bayesian methods*.
Presented at [University of Tübingen](https://uni-tuebingen.de/en/faculties/faculty-of-economics-and-social-sciences/subjects/department-of-social-sciences/methods-center/institute/). 
[Slides](pdf/bayesian_equivalence_testing.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2023). 
Invited talk: *Best Practices for Supervision of Bachelor’s and Master’s Students*. 
Presented at the [International Max Planck Research School for Intelligent Systems](https://imprs.is.mpg.de/).
[Slides](pdf/supervision_workshop.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Aguilar J. E.** & Bürkner P. C. (2023). 
Poster: *Intuitive Joint Priors for Bayesian Multilevel Models: The R2D2M2 Prior*.
Presented at [BayesComp](https://bayescomp2023.com/).
[Slides](pdf/poster_R2D2M2_prior.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://doi.org/10.1214/23-EJS2136){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Schmitt, M.**, Radev, S. T., & Bürkner, P. C. (2023). 
Poster: *Meta-Uncertainty in Bayesian Model Comparison*. 
Presented at [AISTATS](http://aistats.org/aistats2023/).
[Slides](pdf/poster_meta_uncertainty.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://proceedings.mlr.press/v206/schmitt23a.html){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Schmitt, M.**, Bürkner, P. C., Köthe, U., & Radev, S. T. (2023). 
Talk: *Detecting Model Misspecification in Amortized Bayesian Inference with Neural Networks*. 
Presented at the [German Conference on Pattern Recognition](https://www.dagm-gcpr.de/year/2023). 
[Slides](pdf/detecting_MMS_bayesflow.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Poster](pdf/poster_detecting_MMS_bayesflow.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://link.springer.com/chapter/10.1007/978-3-031-54605-1_35){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Schmitt, M.**, Habermann, D., Bürkner, P. C., & Radev, S. T. (2023). 
Talk: *Leveraging Self-Consistency for Data-Efficient Amortized Bayesian Inference*. 
Presented at the [NeurIPS Workshop for Unifying Representations in Neural Models](https://neurips.cc/virtual/2023/workshop/66494).
[Slides](pdf/self_consistency_bayesflow.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2310.04395){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Scholz M.** & Bürkner P.C. (2023). 
Talk: *Prediction can be safely used as a proxy for explanation in causally consistent Bayesian GLMs*.
Presented at [Nordstat](https://nordstat2023.org/). 
[Slides](pdf/prediction_explanation.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2210.06927){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.**, Kröker I., Oladyshkin S., & Nowak W. (2022).
Talk: *The Sparse Bayesian Polynomial Chaos Expansion*. 
Presented at the [DagStat Conference](https://www.dagstat2022.uni-hamburg.de/). 
[Slides](pdf/bayesian_sparse_PCE.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://doi.org/10.1016/j.jcp.2023.112210){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Aguilar J. E.** & Bürkner P. C. (2022). 
Talk: *Intuitive Joint Priors for Bayesian Multilevel Models*
Presented at the [International Conference on Statistics and Data Science](https://sites.google.com/view/icsds2022).
[Slides](pdf/R2D2M2_prior.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://doi.org/10.1214/23-EJS2136){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2022). 
Invited talk: *Probabilistic Learning Theory*. 
Presented at the [Stuttgart ELLIS unit](https://ellis-stuttgart.eu/).
[Slides](pdf/probabilistic_learning_theory.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Youtube](https://www.youtube.com/watch?v=y9Sh6g4X2bM){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2022). 
Invited talk: *Measuring Personality in High-Stakes Situations*.
Presented at the [Interchange Forum for Reflecting on Intelligent Systems](https://www.iris.uni-stuttgart.de/).
[Slides](pdf/measuring_personality_high_stakes.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://link.springer.com/article/10.1007/s11336-022-09843-z){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2021). 
Keynote: *Bayesian Item Response Modeling in R with brms and Stan*.
Presented at the [Psychoco Conference](https://www.psychoco.org/2021/). 
[Slides](pdf/bayesian_IRT_modeling.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Youtube](https://www.youtube.com/watch?v=hwMqnZTa_h8){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://www.jstatsoft.org/article/view/v100i05){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2021). 
Invited talk: *Specifying Priors in a Bayesian Workflow*.
Presented at the [Berlin Bayesian Meetup](https://www.meetup.com/de-DE/BerlinBayesians/).
[Slides](pdf/prior_specification_bayesian_workflow.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Youtube](https://www.youtube.com/watch?v=d6i6xNDmExQ){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2021). 
Keynote: *An introduction to Bayesian multilevel modeling with brms*.
Presented at the [Multilevel Conference](https://multilevel.fss.uu.nl/). 
[Slides](pdf/bayesian_multilevel_modeling_brms.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Youtube](https://www.youtube.com/watch?v=1qeXD4NQ4To){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://www.jstatsoft.org/article/view/v080i01){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2021). 
Invited talk: *Bayesian distributional regression models for cognitive science*.
Presented at [TU Darmstadt University](https://www.tu-darmstadt.de/cogsci/ccs/index.en.jsp).
[Slides](pdf/bayesian_distributional_models.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2021). 
Invited talk: *Introduction to Bayesian Statistics*.
Presented at the [Cluster of Excellence SimTech](https://www.simtech.uni-stuttgart.de/).
[Slides](pdf/introduction_bayesian_statistics.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2021). 
Invited talk: *The Past, Present & Future of brms*.
Presented on [learnbayesstats.com](https://learnbayesstats.com/).
[Potcast](https://learnbayesstats.com/episode/35-past-present-future-brms-paul-burkner/){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Youtube](https://www.youtube.com/watch?v=GLR4ENIkNFY){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Software](../software#brms){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2020). 
Keynote: *A Bayesian Workflow for Data Analysis*.
Presented at the [Summer School on Statistical Methods for Linguistics and Psychology](https://vasishth.github.io/smlp2019/).
[Slides](pdf/bayesian_workflow.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://arxiv.org/abs/2011.01808){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- Vehtari A., Gelman A., Simpson D., Carpenter B., **Bürkner P. C.** (2020). 
Talk: *Improving Convergence Diagnostics for MCMC Sampling Algorithms*.
Presented at the [DGPs Methods Conference](https://www.dgps.de/fachgruppen/methoden-evaluation).
[Slides](pdf/convergence_MCMC.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://doi.org/10.1214/20-BA1221){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.**, Gabry J., & Vehtari A. (2019). 
Talk: *Approximate leave-future-out cross-validation for Bayesian time series models*.
Presented at [StanCon](https://mc-stan.org/events/stancon2019Cambridge/). 
[Slides](pdf/leave_future_out_cross_validation.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Youtube](https://www.youtube.com/watch?v=KH4jN9EBTtE&t=4653s){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://doi.org/10.1080/00949655.2020.1783262){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** & Charpentier E. (2019). 
Talk: *Modeling Monotonic Effects of Ordinal Predictors in Regression Models*.
Presented at the [EAM Conference](https://www.eam-online.org/).
[Slides](pdf/monotonic_effects.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](https://doi.org/10.1111/bmsp.12195){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2019).
Invited talk: *Bayesian model and variable selection using approximate cross-validation and projective predictions*.
Presented at [Imperial College London](https://www.imperial.ac.uk/events/96918/scalable-bayesian-inference-in-applied-fields/). 
[Slides](pdf/bayesian_model_comparison.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2018). 
Talk: *Custom Response Distributions with brms*.
Presented at [StanCon](https://mc-stan.org/events/stancon2018Helsinki/).
[Slides](pdf/custom_response_distributions_brms.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Youtube](https://youtu.be/FoaxA7sJi7w?list=PLuwyh42iHquU4hUBQs20hkBsKSMrp6H0J&t=7985){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Software](../software#brms){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2018).
Invited talk: *From Classical GLMs to Bayesian MLMs*.
Presented at [Insurance Data Science Conference](https://insurancedatascience.org/project/2018_london/).
[Slides](pdf/from_GLMs_to_MLMs.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2018). 
Invited talk: *Bayesian Cognitive Models*.
Presented at the [University of Magdeburg](https://www.ipsy.ovgu.de/en/Our+Institute/Departments/Biological+Psychology.html).
[Slides](pdf/bayesian_cognitive_models.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2017). 
Invited talk: *Optimal Design and Bayesian Data Analysis*.
Presented at the [DGPs Methods Conference](https://uni-tuebingen.de/en/faculties/faculty-of-economics-and-social-sciences/subjects/department-of-social-sciences/methods-center/events/past-events/fgme2017/).
[Slides](pdf/optimal_design_bayesian_data_analysis.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}

- **Bürkner P. C.** (2015). 
Talk: *Optimal Design of Non-Parametric Two-Sample Tests*.
Presented at the [DGPs Methods Conference](https://www.dgps.de/fachgruppen/methoden-evaluation).
[Slides](pdf/optimal_design_two_sample_tests.pdf){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
[Paper](http://onlinelibrary.wiley.com/doi/10.1002/bimj.201600022/full){.btn .btn-outline-primary .btn role="button" .btn-page-header .btn-xs}
