---
layout: post
title: "A list of Blog posts about brms"
modified:
categories: blog
excerpt:
tags: []
image:
  feature:
---

Over the past two years, several people have blogged about my R package **brms**, which allows to fit Bayesian generalized non-linear multilevel models using Stan. This post is indended to provide links to those blog posts.

## List of blog posts

- [R packages interfacing with Stan: brms](http://andrewgelman.com/2017/01/10/r-packages-interfacing-stan-brms/) posted on Andrew Gelmans blog 
- [Bayesian mixed effects (aka multi-level) ordinal regression models with brms](http://kevinstadler.github.io/blog/bayesian-ordinal-regression-with-random-effects-using-brms/) by Kevin Stadler
- [Bayes factors with brms](https://mvuorre.github.io/post/2017/bayes-factors-with-brms/) by Matti Vuorre
- [better forest plots from meta-analytic models estimated with brms](https://mvuorre.github.io/post/2017/better-brms-forest-plots/) by Matti Vuorre
- [brms continuous its streak](https://thinkinator.com/2016/11/20/brms-continues-its-streak/) by Wayne Folta
- [brms 0.8 adds non-linear regression](https://thinkinator.com/2016/02/17/brms-0-8-adds-non-linear-regression/) by Wayne Folta
- [R Users Will Now Inevitably Become Bayesians](https://thinkinator.com/2016/01/12/r-users-will-now-inevitably-become-bayesians/) by Wayne Folta
- [Bayesian regression models using Stan in R ](http://www.magesblog.com/2015/09/bayesian-regression-models-using-stan.html) by Markus Gesmann


